### ISSUE TITLE
Issue with `.name_repair`

### ISSUE THREAD

**Issue by indycool79** [rOpenSpain/climaemet#35]
Hello,

I was trying to create a Walter Lieth climate diagram when I had an error message teling me to report here. The complete error message is:

Error in `ggplot2::geom_segment()`:
! Problem while computing aesthetics.
ℹ Error occurred in the 3rd layer.
Caused by error in `.data$x`:
! Column `x` not found in `.data`.
Run `rlang::last_error()` to see where the error occurred.
Warning message:
The `x` argument of `as_tibble.matrix()` must have unique column names if `.name_repair` is omitted as of
tibble 2.0.0.
ℹ Using compatibility `.name_repair`.
ℹ The deprecated feature was likely used in the climaemet package.
  Please report the issue at <https://github.com/rOpenSpain/climaemet/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

Hope it helps, have a nice day.

**Comment by dieghernan** [comment]
Could you please provide a sample of your data & code? Ideally a full [reprex](https://reprex.tidyverse.org/index.html) so I can figure out

Thanks

**Comment by indycool79** [comment]
Here are the sample and the code

```
#import` data
dat_climat <-
read.csv(file = "dat_climat.csv",
         sep = ";",
         dec = ".")

#create WL diagram
ggclimat_walter_lieth(dat = dat_climat,
                        est="Location Name",
                        alt=40,
                        per="2000-2023",
                        mlab="en",
                        pcol = "blue",
                        tcol = `"red")
```

[dat_climat.csv](https://github.com/rOpenSpain/climaemet/files/10731041/dat_climat.csv)

**Comment by dieghernan** [comment]
Thanks, after #36 I can see

``` r
dat_climat  <- read.csv("https://github.com/rOpenSpain/climaemet/files/10731041/dat_climat.csv",
                        sep = ";",
                        dec = ".")

library(climaemet)
ggclimat_walter_lieth(dat = dat_climat,
                      est="Location Name",
                      alt=40,
                      per="2000-2023",
                      mlab="en",
                      pcol = "blue",
                      tcol = "red")
```

![](https://i.imgur.com/Zpv8AZc.png)

And for double checking, with `climatol::diagwl()` I see:

``` r

library(climatol)
#> Loading required package: maps
#> Loading required package: mapdata

diagwl(dat = dat_climat,
       est="Location Name",
       alt=40,
       per="2000-2023",
       mlab="en",
       pcol = "blue",
       tcol = "red")
```

![](https://i.imgur.com/WomzFJB.png)

<sup>Created on 2023-02-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


Please @indycool79 let me know if that's the expected result

**Comment by indycool79** [comment]
Yes, that's the expected output, thank you!
