### ISSUE TITLE
Review API calls and API Key Management

### ISSUE THREAD

**Issue by dieghernan** [rOpenSpain/climaemet#4]
Potential review of the API Key management and API calls, currently on

https://github.com/rOpenSpain/climaemet/blob/master/R/aemet_api_query.R

https://github.com/rOpenSpain/climaemet/blob/master/R/helpers.R

TODO: Check if this approach is safe and align with current best practices.

Ping @llrs

**Comment by llrs** [comment]
Current recommendations are to move away from .Renviron (leave it just for general R settings) and use specific files for each package (less name collusion or mixing up). Use `rappdirs::user_cache_dir` to create a directory to store the API key in a file. 

The functionality of a query could be split in several functions: check input, make queries, check response, tidy/organize response. 

I would also simplify the api query string by expanding the base_url (to have also the /api/ part). But I don't know good enough the resource to see if more optimizations could be done (I've seen the queries are not via a parameter but directly on a different url). 


Also if users usually only have one API key do not require it as argument on each function. Instead set it once for the package/session and use it. I would recommend to store the API key on an environment for that. 


-----
Some other feedback:
I would recommend to avoid sending message .onLoad as it clutters users terminal. 

There are also some folders I think they are not needed (dev). There seems to be some files for examples or README on inst/examples, data and data-raw not sure which are needed and which aren't.

Last, I personally don't like to provide plotting functions for the data I provide on a package just have some examples on the vignette or README and let the user create what they see fit.

**Comment by dieghernan** [comment]
Thank you very much for this. Some additional comments from my side:
- I would follow your advice on the API key storage and management, I would figure out an approach that doesn’t modify `.Renviron` (I was a bit uncomfortable with that, honestly).
- I think is a good idea to simplify the api query string, thanks, I would do.
- I think `apikey` on functions can be soft/warn-deprecated on this version and hard-deprecated on an upcoming release. This definitely would be a breaking change regarding the current CRAN version.
- I don’t specially like .onLoad() messages, but given the breaking changes I am introducing I felt that I needed to inform the users. They can be suppressed with `suppressPackageStartupMessages`.
- You are right with `dev` folder. Regarding `inst/examples`, those are the examples included on some `man` via `#' @example inst/examples/file.R` instead of copy/pasting them: 
> Instead of including examples directly in the documentation, you can put them in separate files and use @example path/relative/to/package/root to insert them into the documentation.

https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html

- Fully agree with your view on plots, but again it would be breaking and I guess @mpizarrotig included them for a good reason. Those are special plot composition for climatic data, in the end are just processing and templating processes that may be not so easy to achieve if you are not familiar with `ggplot2`.

Thanks for your time on this, I would share with you my solution on the API key management, regards

**Comment by dieghernan** [comment]
Finally I decided to remove the `apikey` parameter on all the functions. As this would be anyway a new major version I felt that it was the right moment to do it.

I modified also the storage of the API Key, see https://github.com/rOpenSpain/climaemet/blob/master/R/aemet_api_key.R

Now `aemet_detect_api_key` not only detects but also loads the cached API key if AEMET_API_KEY is empty, and this is checked before every api query.

I hope this is more aligned with current best practices @llrs , thank you very much

**Comment by llrs** [comment]
Note to myself that also affects the changes I recommended previously: On new R versions (R > 4.0) there's the tools::R_user_dir which can be used for data, config and cache. (So you don't need to depend on an external package to do so). The path are different but the intention is the same.

**Comment by dieghernan** [comment]
Just for info, this is the source code of tools::R_user_dir() 

https://github.com/wch/r-source/blob/trunk/src/library/tools/R/userdir.R
