### ISSUE TITLE
Include articles on spatial interpolation

### ISSUE THREAD

**Issue by dieghernan** [rOpenSpain/climaemet#6]
Following @mpizarrotig , we may include some information (proposal: as `pkgdown` [article](https://usethis.r-lib.org/reference/use_vignette.html) rather than function on package) on how to use climaemet to create interpolated maps with climatological values  *à la @dominicroye* (see https://dominicroye.github.io/en/2020/climate-animation-of-maximum-temperatures/).

Some advances already made by @verajosemanuel on https://github.com/verajosemanuel/pruebainterpolar/blob/master/interpolacion_ejemplo.md. With climaemet data, interpolation would be needed to increase granularity and covering the whole country, as AEMET provides information at station level only.

Base maps can be obtained via [mapSpain](https://github.com/ropenspain/mapSpain) (idea: PNOA tiles overlayed with interpolated temperatures??)

**Comment by verajosemanuel** [comment]
Working on the function. The geometry could be from mapSpain or SHP file provided by user. 
But when using a shp file an error is raised (to my knowledge, come cleaning is needed in case of null values): 

```
raster::extract(r, codigos_postales)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'addAttrToGeom': empty geometries are not supported by sp classes: conversion failed
```
